In [20]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
df2=pd.read_csv("./data/Census_Income_Data Set2.csv")
df2.head(4)

Unnamed: 0  age          workclass  fnlwgt   education  education-num   
0           0   39          State-gov   77516   Bachelors             13  \
1           1   50   Self-emp-not-inc   83311   Bachelors             13   
2           2   38            Private  215646     HS-grad              9   
3           3   53            Private  234721        11th              7   

        marital-status          occupation    relationship    race    sex   
0        Never-married        Adm-clerical   Not-in-family   White   Male  \
1   Married-civ-spouse     Exec-managerial         Husband   White   Male   
2             Divorced   Handlers-cleaners   Not-in-family   White   Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black   Male   

   capital-gain  capital-loss  hours-per-week  native-country  Income  
0          2174             0              40   United-States       0  
1             0             0              13   United-States       0  
2             0             0              40   United-States       0  
3             0             0              40   United-States       0

In [21]:
df2.shape

(32537, 16)

In [22]:
# Replacing missing values by mode this values are present in categorical columns
df2['workclass']=df2['workclass'].str.replace("?","Private")
df2['occupation']=df2['occupation'].str.replace("?","Prof-specialty")
df2['native-country']=df2['native-country'].str.replace("?","United-States")

In [23]:
df2=df2.drop_duplicates()

In [24]:

#df2['Income']=df2['Income'].str.replace("<=50K","0")
#df2['Income']=df2['Income'].str.replace(">50K","1")

In [25]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32537 entries, 0 to 32536
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Unnamed: 0      32537 non-null  int64 
 1   age             32537 non-null  int64 
 2   workclass       32537 non-null  object
 3   fnlwgt          32537 non-null  int64 
 4   education       32537 non-null  object
 5   education-num   32537 non-null  int64 
 6   marital-status  32537 non-null  object
 7   occupation      32537 non-null  object
 8   relationship    32537 non-null  object
 9   race            32537 non-null  object
 10  sex             32537 non-null  object
 11  capital-gain    32537 non-null  int64 
 12  capital-loss    32537 non-null  int64 
 13  hours-per-week  32537 non-null  int64 
 14  native-country  32537 non-null  object
 15  Income          32537 non-null  int64 
dtypes: int64(8), object(8)
memory usage: 4.0+ MB


In [26]:
df2['Income']=df2['Income'].astype('int64')

In [27]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32537 entries, 0 to 32536
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Unnamed: 0      32537 non-null  int64 
 1   age             32537 non-null  int64 
 2   workclass       32537 non-null  object
 3   fnlwgt          32537 non-null  int64 
 4   education       32537 non-null  object
 5   education-num   32537 non-null  int64 
 6   marital-status  32537 non-null  object
 7   occupation      32537 non-null  object
 8   relationship    32537 non-null  object
 9   race            32537 non-null  object
 10  sex             32537 non-null  object
 11  capital-gain    32537 non-null  int64 
 12  capital-loss    32537 non-null  int64 
 13  hours-per-week  32537 non-null  int64 
 14  native-country  32537 non-null  object
 15  Income          32537 non-null  int64 
dtypes: int64(8), object(8)
memory usage: 4.0+ MB


In [28]:
#df2.to_csv("Census_Income_DataSet2.csv")

In [29]:
df2['education-num']=df2['education-num'].astype('int64')

In [30]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32537 entries, 0 to 32536
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Unnamed: 0      32537 non-null  int64 
 1   age             32537 non-null  int64 
 2   workclass       32537 non-null  object
 3   fnlwgt          32537 non-null  int64 
 4   education       32537 non-null  object
 5   education-num   32537 non-null  int64 
 6   marital-status  32537 non-null  object
 7   occupation      32537 non-null  object
 8   relationship    32537 non-null  object
 9   race            32537 non-null  object
 10  sex             32537 non-null  object
 11  capital-gain    32537 non-null  int64 
 12  capital-loss    32537 non-null  int64 
 13  hours-per-week  32537 non-null  int64 
 14  native-country  32537 non-null  object
 15  Income          32537 non-null  int64 
dtypes: int64(8), object(8)
memory usage: 4.0+ MB


In [31]:
## Independent and Dependent features
X=df2.drop(labels=['Income'],axis=1)
Y=df2[['Income']]

In [32]:
## Define which columns should be ordinal-encoded which should be scaled
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

In [33]:
# Define one hot encoded variables
workclass_cat=['State-gov','Self-emp-inc','Private','Federal-gov','Local-gov','Self-emp-inc','Without-pay','Never-worked']
education_cat=['Bachelors','HS-grad','11th','Masters','9th','Some-college','Assoc-acdm','Assoc-voc','7th-8th','Doctorate','Prof-school','5th-6th','10th','1st-4th','Preschool','12th']
marital_status_cat=['Never-married','Married-civ-spouse','Divorced','Married-spouse-absent','Separated','Married-AF-spouse','Widowed']
occupation_cat=['Adm-clerical','Exec-managerial','Handlers-cleaners','Prof-specialty','Other-service','Sales','Craft-repair','Transport-moving','Farming-fishing','Machine-op-inspct','Tech-support','Protective-serv','Armed-Forces','Priv-house-serv']
relationship_cat=['Not-in-family','Husband','Wife','Own-child','Unmarried','Other-relative']
race_cat=['White','Black','Asian-Pac-Islander','Amer-Indian-Eskimo','Other']
sex_cat=['Male','Female']
native_country_cat=['United-States','Cuba','Jamaica','India','Mexico','South','Puerto-Rico','Honduras','England','Canada','Germany','Iran','Philippines','Italy','Poland','Columbia','Cambodia','Thailand','Ecuador','Laos','Taiwan','Haiti','Portugal','Dominican-Republic','El-Salvador','France','Guatemala','China','Japan','Yugoslavia','Peru','Outlying-US(Guam-USVI-etc)','Scotland','Trinadad&Tobago','Greece',' Nicaragua','Vietnam','Hong','Ireland','Hungary','Holand-Netherlands']

In [34]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OneHotEncoder #  Onehotencoder Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [35]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),
        ('scaler',StandardScaler())
    ]
)

## Categorical Pipeline
cat_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('ordinalEncoder',OneHotEncoder(sparse_output=False,handle_unknown='error')),
        ('scaler',StandardScaler())
    ]

)

preprocesser=ColumnTransformer([
    ('num_pipeline',num_pipeline,numerical_cols),
    ('cat_pipeline',cat_pipeline,categorical_cols)
])

In [36]:
# Train Test-Split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=42)

In [37]:
X_train

Unnamed: 0  age          workclass  fnlwgt      education   
1216         1216   48   Self-emp-not-inc  243631   Some-college  \
27941       27958   31            Private  241360      Bachelors   
23063       23078   50            Private   43764      Doctorate   
19670       19679   22            Private  189888        HS-grad   
19172       19181   28            Private  107411        HS-grad   
...           ...  ...                ...     ...            ...   
29802       29823   38            Private  187983    Prof-school   
5390         5392   63            Private  216413      Bachelors   
860           860   18            Private  216284           11th   
15795       15801   34            Private  242960      Assoc-voc   
23654       23669   23            Private  329925   Some-college   

       education-num       marital-status          occupation    relationship   
1216              10   Married-civ-spouse        Craft-repair         Husband  \
27941             13        Never-married               Sales   Not-in-family   
23063             16   Married-civ-spouse      Prof-specialty         Husband   
19670              9   Married-civ-spouse               Sales         Husband   
19172              9        Never-married     Exec-managerial   Not-in-family   
...              ...                  ...                 ...             ...   
29802             15   Married-civ-spouse               Sales            Wife   
5390              13              Widowed        Adm-clerical   Not-in-family   
860                7        Never-married        Adm-clerical       Own-child   
15795             11   Married-civ-spouse        Craft-repair         Husband   
23654             10        Never-married   Handlers-cleaners       Own-child   

                      race      sex  capital-gain  capital-loss   
1216    Amer-Indian-Eskimo     Male          7688             0  \
27941                White     Male             0             0   
23063                White     Male         15024             0   
19670                White     Male             0             0   
19172                White   Female             0             0   
...                    ...      ...           ...           ...   
29802                White   Female             0             0   
5390                 White   Female             0             0   
860                  White   Female             0             0   
15795                White     Male             0             0   
23654                White     Male             0             0   

       hours-per-week  native-country  
1216               40   United-States  
27941              40   United-States  
23063              50   United-States  
19670              45   United-States  
19172              45   United-States  
...               ...             ...  
29802              40   United-States  
5390               25   United-States  
860                20   United-States  
15795              50   United-States  
23654              30   United-States  

[22775 rows x 15 columns]

In [38]:
X_train=pd.DataFrame(preprocesser.fit_transform(X_train),columns=preprocesser.get_feature_names_out())
X_test=pd.DataFrame(preprocesser.transform(X_test),columns=preprocesser.get_feature_names_out())
X_train.head()

num_pipeline__Unnamed: 0  num_pipeline__age  num_pipeline__fnlwgt   
0                 -1.603857           0.693443              0.503319  \
1                  1.242129          -0.555208              0.481795   
2                  0.722781           0.840343             -1.391011   
3                  0.361046          -1.216259             -0.006054   
4                  0.308047          -0.775558             -0.787768   

   num_pipeline__education-num  num_pipeline__capital-gain   
0                    -0.033365                    0.917418  \
1                     1.135080                   -0.142880   
2                     2.303525                    1.929169   
3                    -0.422846                   -0.142880   
4                    -0.422846                   -0.142880   

   num_pipeline__capital-loss  num_pipeline__hours-per-week   
0                   -0.219029                     -0.033058  \
1                   -0.219029                     -0.033058   
2                   -0.219029                      0.777388   
3                   -0.219029                      0.372165   
4                   -0.219029                      0.372165   

   cat_pipeline__workclass_ Federal-gov  cat_pipeline__workclass_ Local-gov   
0                             -0.174097                           -0.259894  \
1                             -0.174097                           -0.259894   
2                             -0.174097                           -0.259894   
3                             -0.174097                           -0.259894   
4                             -0.174097                           -0.259894   

   cat_pipeline__workclass_ Never-worked  ...   
0                              -0.013254  ...  \
1                              -0.013254  ...   
2                              -0.013254  ...   
3                              -0.013254  ...   
4                              -0.013254  ...   

   cat_pipeline__native-country_ Portugal   
0                                -0.03315  \
1                                -0.03315   
2                                -0.03315   
3                                -0.03315   
4                                -0.03315   

   cat_pipeline__native-country_ Puerto-Rico   
0                                  -0.061206  \
1                                  -0.061206   
2                                  -0.061206   
3                                  -0.061206   
4                                  -0.061206   

   cat_pipeline__native-country_ Scotland   
0                               -0.018745  \
1                               -0.018745   
2                               -0.018745   
3                               -0.018745   
4                               -0.018745   

   cat_pipeline__native-country_ South  cat_pipeline__native-country_ Taiwan   
0                            -0.049201                             -0.041945  \
1                            -0.049201                             -0.041945   
2                            -0.049201                             -0.041945   
3                            -0.049201                             -0.041945   
4                            -0.049201                             -0.041945   

   cat_pipeline__native-country_ Thailand   
0                               -0.023898  \
1                               -0.023898   
2                               -0.023898   
3                               -0.023898   
4                               -0.023898   

   cat_pipeline__native-country_ Trinadad&Tobago   
0                                      -0.023898  \
1                                      -0.023898   
2                                      -0.023898   
3                                      -0.023898   
4                                      -0.023898   

   cat_pipeline__native-country_ United-States   
0                                     0.310528  \
1                                     0.310528   
2 

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.metrics import log_loss

In [40]:
log_model=LogisticRegression()
dec_model=DecisionTreeClassifier()

In [41]:
log_model.fit(X_train,y_train)

LogisticRegression()

In [42]:
log_model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [43]:
log_model.score(X_train,y_train)

0.8517233809001098

In [44]:
dec_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [45]:
dec_model.score(X_train,y_train)

1.0

In [46]:
log_model.coef_

array([[ 4.12608004e-03,  2.92120662e-01,  5.81520469e-02,
         3.93988782e-01,  2.30852515e+00,  2.81789181e-01,
         3.70945335e-01,  1.03639171e-01,  1.28433606e-02,
        -8.00931185e-02,  1.96233939e-02,  5.81574672e-02,
        -1.20127643e-01, -2.22360321e-02, -1.24306199e-01,
        -8.26277181e-02, -8.78545653e-02, -4.32844392e-02,
        -1.92569657e-02, -9.89999478e-02, -8.40220434e-02,
        -7.62587665e-02, -2.47469037e-02, -5.15064604e-04,
         1.46810863e-01,  1.33419921e-01, -8.08937362e-02,
         1.68870415e-01, -4.65370634e-01,  1.46651113e-01,
         5.73532438e-03, -1.81760575e-01,  5.46044867e-02,
         6.49061770e-01, -5.47870338e-02, -4.81450322e-01,
        -1.24184409e-01, -4.82302771e-02, -4.66043694e-03,
        -1.81108387e-02,  3.46042819e-02,  2.52184303e-01,
        -1.74911348e-01, -1.30058398e-01, -8.46996826e-02,
        -2.38943545e-01, -2.73638528e-01,  4.84925649e-02,
         7.52105598e-02,  9.67065418e-02,  1.07539394e-0

In [47]:
log_model.intercept_

array([-2.08516891])

In [48]:
parameters={'penalty':['l1', 'l2', 'elasticnet'],'C':[1,2,3,4,5,6,10,20,30,40,50],'max_iter':[100,200,300,400,500]}

In [49]:
model_logistic=GridSearchCV(log_model,param_grid=parameters,scoring='accuracy',cv=5)

In [50]:
model_logistic.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 10, 20, 30, 40, 50],
                         'max_iter': [100, 200, 300, 400, 500],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             scoring='accuracy')

In [51]:
model_logistic.best_params_

{'C': 5, 'max_iter': 100, 'penalty': 'l2'}

In [52]:
print(model_logistic.best_score_)

0.8500548847420417


In [53]:
param_grid={
    'max_depth':[3,4,5,6],
    'min_samples_split':[2,3,4,5],
    'min_samples_leaf':[1,2,3]
}

In [54]:
decisiontree_model=GridSearchCV(dec_model,param_grid=param_grid,cv=5)

In [55]:
decisiontree_model.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [3, 4, 5, 6],
                         'min_samples_leaf': [1, 2, 3],
                         'min_samples_split': [2, 3, 4, 5]})

In [56]:
decisiontree_model.best_params_

{'max_depth': 6, 'min_samples_leaf': 2, 'min_samples_split': 4}

In [57]:
print(decisiontree_model.best_score_)

0.8541383095499452


In [58]:
import numpy as np
def model_evalute(true,predicted):
     acc_score=accuracy_score(true,predicted)
     logloss=log_loss(true,predicted)
     classification_Report=classification_report(true,predicted)
     Confusion_Matrix=confusion_matrix(true,predicted)
     return acc_score,logloss,classification_Report,Confusion_Matrix

In [59]:
# Train Multiple Models

models={

    'LogisticRegression':LogisticRegression(random_state=42),
    'DecisionTreeClassifier':DecisionTreeClassifier(max_depth=6, min_samples_leaf=3, min_samples_split=5,random_state=42)
    
}

model_list=[]
acc_score_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    # Make Predictions
    y_pred=model.predict(X_test)

    acc_score,logloss,classification_Report,Confusion_Matrix=model_evalute(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print('Accuracy Score',acc_score*100)
    print('Log Loss',logloss)
    print('Classification Report',"\n",
          classification_Report)
    print('Confusion Matrix','\n',
          Confusion_Matrix)
    print("="*35)
    print('\n')

    acc_score_list.append(acc_score)
 

LogisticRegression
Model Training Performance
Accuracy Score 85.24892440073756
Log Loss 5.316826560164792
Classification Report 
               precision    recall  f1-score   support

           0       0.88      0.93      0.91      7405
           1       0.74      0.61      0.67      2357

    accuracy                           0.85      9762
   macro avg       0.81      0.77      0.79      9762
weighted avg       0.85      0.85      0.85      9762

Confusion Matrix 
 [[6889  516]
 [ 924 1433]]


DecisionTreeClassifier
Model Training Performance
Accuracy Score 85.49477566072527
Log Loss 5.2282127841620465
Classification Report 
               precision    recall  f1-score   support

           0       0.87      0.95      0.91      7405
           1       0.79      0.55      0.65      2357

    accuracy                           0.85      9762
   macro avg       0.83      0.75      0.78      9762
weighted avg       0.85      0.85      0.85      9762

Confusion Matrix 
 [[7058  347]
 

In [60]:
model_list

['LogisticRegression', 'DecisionTreeClassifier']

In [61]:
acc_score_list

[0.8524892440073756, 0.8549477566072526]