In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
df2=pd.read_csv("./data/Census_Income_Data_Set1.csv")
df2.head(4)

age          workclass  fnlwgt   education  education_num   
0   39          State-gov   77516   Bachelors             13  \
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   

        marital_status          occupation    relationship    race    sex   
0        Never-married        Adm-clerical   Not-in-family   White   Male  \
1   Married-civ-spouse     Exec-managerial         Husband   White   Male   
2             Divorced   Handlers-cleaners   Not-in-family   White   Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black   Male   

   capital_gain  capital_loss  hours_per_week  native_country  Income  
0          2174             0              40   United-States       0  
1             0             0              13   United-States       0  
2             0             0              40   United-States       0  
3             0             0              40   United-States       0

In [2]:
df2.shape

(32537, 15)

In [3]:
# Replacing missing values by mode this values are present in categorical columns
#df2['workclass']=df2['workclass'].str.replace("?","Private")
#df2['occupation']=df2['occupation'].str.replace("?","Prof-specialty")
#df2['native-country']=df2['native-country'].str.replace("?","United-States")

In [4]:
#df2=df2.drop_duplicates()

In [5]:

#df2['Income']=df2['Income'].str.replace("<=50K","0")
#df2['Income']=df2['Income'].str.replace(">50K","1")

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32537 entries, 0 to 32536
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32537 non-null  int64 
 1   workclass       32537 non-null  object
 2   fnlwgt          32537 non-null  int64 
 3   education       32537 non-null  object
 4   education_num   32537 non-null  int64 
 5   marital_status  32537 non-null  object
 6   occupation      32537 non-null  object
 7   relationship    32537 non-null  object
 8   race            32537 non-null  object
 9   sex             32537 non-null  object
 10  capital_gain    32537 non-null  int64 
 11  capital_loss    32537 non-null  int64 
 12  hours_per_week  32537 non-null  int64 
 13  native_country  32537 non-null  object
 14  Income          32537 non-null  int64 
dtypes: int64(7), object(8)
memory usage: 3.7+ MB


In [7]:
#df2['Income']=df2['Income'].astype('int64')

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32537 entries, 0 to 32536
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32537 non-null  int64 
 1   workclass       32537 non-null  object
 2   fnlwgt          32537 non-null  int64 
 3   education       32537 non-null  object
 4   education_num   32537 non-null  int64 
 5   marital_status  32537 non-null  object
 6   occupation      32537 non-null  object
 7   relationship    32537 non-null  object
 8   race            32537 non-null  object
 9   sex             32537 non-null  object
 10  capital_gain    32537 non-null  int64 
 11  capital_loss    32537 non-null  int64 
 12  hours_per_week  32537 non-null  int64 
 13  native_country  32537 non-null  object
 14  Income          32537 non-null  int64 
dtypes: int64(7), object(8)
memory usage: 3.7+ MB


In [9]:
#df2.to_csv("Census_Income_DataSet2.csv")

In [10]:
#df2['education-num']=df2['education-num'].astype('int64')

In [11]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32537 entries, 0 to 32536
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32537 non-null  int64 
 1   workclass       32537 non-null  object
 2   fnlwgt          32537 non-null  int64 
 3   education       32537 non-null  object
 4   education_num   32537 non-null  int64 
 5   marital_status  32537 non-null  object
 6   occupation      32537 non-null  object
 7   relationship    32537 non-null  object
 8   race            32537 non-null  object
 9   sex             32537 non-null  object
 10  capital_gain    32537 non-null  int64 
 11  capital_loss    32537 non-null  int64 
 12  hours_per_week  32537 non-null  int64 
 13  native_country  32537 non-null  object
 14  Income          32537 non-null  int64 
dtypes: int64(7), object(8)
memory usage: 3.7+ MB


In [12]:
## Independent and Dependent features
X=df2.drop(labels=['Income'],axis=1)
Y=df2[['Income']]

In [13]:
## Define which columns should be ordinal-encoded which should be scaled
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

In [14]:
# Define one hot encoded variables
workclass_cat=['State-gov','Self-emp-inc','Private','Federal-gov','Local-gov','Self-emp-inc','Without-pay','Never-worked']
education_cat=['Bachelors','HS-grad','11th','Masters','9th','Some-college','Assoc-acdm','Assoc-voc','7th-8th','Doctorate','Prof-school','5th-6th','10th','1st-4th','Preschool','12th']
marital_status_cat=['Never-married','Married-civ-spouse','Divorced','Married-spouse-absent','Separated','Married-AF-spouse','Widowed']
occupation_cat=['Adm-clerical','Exec-managerial','Handlers-cleaners','Prof-specialty','Other-service','Sales','Craft-repair','Transport-moving','Farming-fishing','Machine-op-inspct','Tech-support','Protective-serv','Armed-Forces','Priv-house-serv']
relationship_cat=['Not-in-family','Husband','Wife','Own-child','Unmarried','Other-relative']
race_cat=['White','Black','Asian-Pac-Islander','Amer-Indian-Eskimo','Other']
sex_cat=['Male','Female']
native_country_cat=['United-States','Cuba','Jamaica','India','Mexico','South','Puerto-Rico','Honduras','England','Canada','Germany','Iran','Philippines','Italy','Poland','Columbia','Cambodia','Thailand','Ecuador','Laos','Taiwan','Haiti','Portugal','Dominican-Republic','El-Salvador','France','Guatemala','China','Japan','Yugoslavia','Peru','Outlying-US(Guam-USVI-etc)','Scotland','Trinadad&Tobago','Greece',' Nicaragua','Vietnam','Hong','Ireland','Hungary','Holand-Netherlands']

In [15]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OneHotEncoder #  Onehotencoder Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [16]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),
        ('scaler',StandardScaler())
    ]
)

## Categorical Pipeline
cat_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('ordinalEncoder',OneHotEncoder(sparse_output=False,handle_unknown='error')),
        ('scaler',StandardScaler())
    ]

)

preprocesser=ColumnTransformer([
    ('num_pipeline',num_pipeline,numerical_cols),
    ('cat_pipeline',cat_pipeline,categorical_cols)
])

In [17]:
# Train Test-Split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=42)

In [18]:
X_train

age          workclass  fnlwgt      education  education_num   
1216    48   Self-emp-not-inc  243631   Some-college             10  \
27941   31            Private  241360      Bachelors             13   
23063   50            Private   43764      Doctorate             16   
19670   22            Private  189888        HS-grad              9   
19172   28            Private  107411        HS-grad              9   
...    ...                ...     ...            ...            ...   
29802   38            Private  187983    Prof-school             15   
5390    63            Private  216413      Bachelors             13   
860     18            Private  216284           11th              7   
15795   34            Private  242960      Assoc-voc             11   
23654   23            Private  329925   Some-college             10   

            marital_status          occupation    relationship   
1216    Married-civ-spouse        Craft-repair         Husband  \
27941        Never-married               Sales   Not-in-family   
23063   Married-civ-spouse      Prof-specialty         Husband   
19670   Married-civ-spouse               Sales         Husband   
19172        Never-married     Exec-managerial   Not-in-family   
...                    ...                 ...             ...   
29802   Married-civ-spouse               Sales            Wife   
5390               Widowed        Adm-clerical   Not-in-family   
860          Never-married        Adm-clerical       Own-child   
15795   Married-civ-spouse        Craft-repair         Husband   
23654        Never-married   Handlers-cleaners       Own-child   

                      race      sex  capital_gain  capital_loss   
1216    Amer-Indian-Eskimo     Male          7688             0  \
27941                White     Male             0             0   
23063                White     Male         15024             0   
19670                White     Male             0             0   
19172                White   Female             0             0   
...                    ...      ...           ...           ...   
29802                White   Female             0             0   
5390                 White   Female             0             0   
860                  White   Female             0             0   
15795                White     Male             0             0   
23654                White     Male             0             0   

       hours_per_week  native_country  
1216               40   United-States  
27941              40   United-States  
23063              50   United-States  
19670              45   United-States  
19172              45   United-States  
...               ...             ...  
29802              40   United-States  
5390               25   United-States  
860                20   United-States  
15795              50   United-States  
23654              30   United-States  

[22775 rows x 14 columns]

In [19]:
X_train=pd.DataFrame(preprocesser.fit_transform(X_train),columns=preprocesser.get_feature_names_out())
X_test=pd.DataFrame(preprocesser.transform(X_test),columns=preprocesser.get_feature_names_out())
X_train.head()

num_pipeline__age  num_pipeline__fnlwgt  num_pipeline__education_num   
0           0.693443              0.503319                    -0.033365  \
1          -0.555208              0.481795                     1.135080   
2           0.840343             -1.391011                     2.303525   
3          -1.216259             -0.006054                    -0.422846   
4          -0.775558             -0.787768                    -0.422846   

   num_pipeline__capital_gain  num_pipeline__capital_loss   
0                    0.917418                   -0.219029  \
1                   -0.142880                   -0.219029   
2                    1.929169                   -0.219029   
3                   -0.142880                   -0.219029   
4                   -0.142880                   -0.219029   

   num_pipeline__hours_per_week  cat_pipeline__workclass_ Federal-gov   
0                     -0.033058                             -0.174097  \
1                     -0.033058                             -0.174097   
2                      0.777388                             -0.174097   
3                      0.372165                             -0.174097   
4                      0.372165                             -0.174097   

   cat_pipeline__workclass_ Local-gov  cat_pipeline__workclass_ Never-worked   
0                           -0.259894                              -0.013254  \
1                           -0.259894                              -0.013254   
2                           -0.259894                              -0.013254   
3                           -0.259894                              -0.013254   
4                           -0.259894                              -0.013254   

   cat_pipeline__workclass_ Private  ...   
0                         -1.752520  ...  \
1                          0.570607  ...   
2                          0.570607  ...   
3                          0.570607  ...   
4                          0.570607  ...   

   cat_pipeline__native_country_ Portugal   
0                                -0.03315  \
1                                -0.03315   
2                                -0.03315   
3                                -0.03315   
4                                -0.03315   

   cat_pipeline__native_country_ Puerto-Rico   
0                                  -0.061206  \
1                                  -0.061206   
2                                  -0.061206   
3                                  -0.061206   
4                                  -0.061206   

   cat_pipeline__native_country_ Scotland   
0                               -0.018745  \
1                               -0.018745   
2                               -0.018745   
3                               -0.018745   
4                               -0.018745   

   cat_pipeline__native_country_ South  cat_pipeline__native_country_ Taiwan   
0                            -0.049201                             -0.041945  \
1                            -0.049201                             -0.041945   
2                            -0.049201                             -0.041945   
3                            -0.049201                             -0.041945   
4                            -0.049201                             -0.041945   

   cat_pipeline__native_country_ Thailand   
0                               -0.023898  \
1                               -0.023898   
2                               -0.023898   
3                               -0.023898   
4                               -0.023898   

   cat_pipeline__native_country_ Trinadad&Tobago   
0                                      -0.023898  \
1                                      -0.023898   
2                                      -0.023898   
3                                      -0.023898   
4                                      -0.023898   

   cat_pipeline__native_country_ United-States   
0                                     0.310528  \
1   

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.metrics import log_loss

In [21]:
log_model=LogisticRegression()
dec_model=DecisionTreeClassifier()

In [22]:
log_model.fit(X_train,y_train)

LogisticRegression()

In [23]:
log_model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
log_model.score(X_train,y_train)

0.8517672886937432

In [25]:
dec_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [26]:
dec_model.score(X_train,y_train)

0.9999560922063666

In [27]:
log_model.coef_

array([[ 2.92139179e-01,  5.81413981e-02,  3.94189906e-01,
         2.30859767e+00,  2.81812242e-01,  3.70985457e-01,
         1.03645138e-01,  1.28219814e-02, -7.86960068e-02,
         1.95855392e-02,  5.81088379e-02, -1.20185589e-01,
        -2.22544317e-02, -1.22705007e-01, -8.25840553e-02,
        -8.78594786e-02, -4.31652871e-02, -1.91987973e-02,
        -9.90041112e-02, -8.38574049e-02, -7.62403450e-02,
        -2.47257936e-02, -4.96963236e-04,  1.46757743e-01,
         1.33430917e-01, -8.08214578e-02,  1.68824286e-01,
        -4.67710086e-01,  1.46653133e-01,  5.81826674e-03,
        -1.81811601e-01,  5.45938387e-02,  6.49137460e-01,
        -5.48800616e-02, -4.81483769e-01, -1.24208100e-01,
        -4.81698924e-02, -4.69646566e-03, -1.80892738e-02,
         3.46303717e-02,  2.52191691e-01, -1.74863054e-01,
        -1.30005563e-01, -8.46920014e-02, -2.38900397e-01,
        -2.74266067e-01,  4.85246443e-02,  7.52233727e-02,
         9.66796814e-02,  1.07548133e-01, -1.30048470e-0

In [28]:
log_model.intercept_

array([-2.08499911])

In [29]:
parameters={'penalty':['l1', 'l2', 'elasticnet'],'C':[1,2,3,4,5,6,10,20,30,40,50],'max_iter':[100,200,300,400,500]}

In [30]:
model_logistic=GridSearchCV(log_model,param_grid=parameters,scoring='accuracy',cv=5)

In [31]:
model_logistic.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 10, 20, 30, 40, 50],
                         'max_iter': [100, 200, 300, 400, 500],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             scoring='accuracy')

In [32]:
model_logistic.best_params_

{'C': 1, 'max_iter': 100, 'penalty': 'l2'}

In [33]:
print(model_logistic.best_score_)

0.8500548847420417


In [34]:
param_grid={
    'max_depth':[3,4,5,6],
    'min_samples_split':[2,3,4,5],
    'min_samples_leaf':[1,2,3]
}

In [35]:
decisiontree_model=GridSearchCV(dec_model,param_grid=param_grid,cv=5)

In [36]:
decisiontree_model.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [3, 4, 5, 6],
                         'min_samples_leaf': [1, 2, 3],
                         'min_samples_split': [2, 3, 4, 5]})

In [37]:
decisiontree_model.best_params_

{'max_depth': 6, 'min_samples_leaf': 1, 'min_samples_split': 3}

In [38]:
print(decisiontree_model.best_score_)

0.8541822173435787


In [39]:
import numpy as np
def model_evalute(true,predicted):
     acc_score=accuracy_score(true,predicted)
     logloss=log_loss(true,predicted)
     classification_Report=classification_report(true,predicted)
     Confusion_Matrix=confusion_matrix(true,predicted)
     return acc_score,logloss,classification_Report,Confusion_Matrix

In [40]:
# Train Multiple Models

models={

'LogisticRegression':LogisticRegression(random_state=42),
'DecisionTreeClassifier':DecisionTreeClassifier(max_depth=6, min_samples_leaf=3, min_samples_split=5,random_state=42)
    
}

model_list=[]
acc_score_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    # Make Predictions
    y_pred=model.predict(X_test)

    acc_score,logloss,classification_Report,Confusion_Matrix=model_evalute(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print('Accuracy Score',acc_score*100)
    print('Log Loss',logloss)
    print('Classification Report',"\n",
          classification_Report)
    print('Confusion Matrix','\n',
          Confusion_Matrix)
    print("="*35)
    print('\n')

    acc_score_list.append(acc_score)
 

LogisticRegression
Model Training Performance
Accuracy Score 85.22843679573859
Log Loss 5.324211041498354
Classification Report 
               precision    recall  f1-score   support

           0       0.88      0.93      0.91      7405
           1       0.73      0.61      0.67      2357

    accuracy                           0.85      9762
   macro avg       0.81      0.77      0.79      9762
weighted avg       0.85      0.85      0.85      9762

Confusion Matrix 
 [[6887  518]
 [ 924 1433]]


DecisionTreeClassifier
Model Training Performance
Accuracy Score 85.47428805572629
Log Loss 5.235597265495608
Classification Report 
               precision    recall  f1-score   support

           0       0.87      0.95      0.91      7405
           1       0.79      0.55      0.64      2357

    accuracy                           0.85      9762
   macro avg       0.83      0.75      0.78      9762
weighted avg       0.85      0.85      0.84      9762

Confusion Matrix 
 [[7058  347]
 [

In [41]:
model_list

['LogisticRegression', 'DecisionTreeClassifier']

In [42]:
acc_score_list

[0.8522843679573858, 0.8547428805572629]